# Generated by Django 5.2.17 on 2026-10-01 02:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_user_approval'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='language',
            field=models.CharField(blank=True, choices=[('ar', 'العربية'), ('en', 'English')], max_length=5, verbose_name='اللغة'),
        ),
    ]
