# Generated by Django 5.2.17 on 2026-09-30 13:54

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='اسم الشركة')),
                ('slug', models.SlugField(allow_unicode=True, max_length=170, unique=True)),
                ('logo', models.ImageField(blank=True, upload_to='logos/', verbose_name='الشعار')),
                ('industry', models.CharField(max_length=150, verbose_name='المجال')),
                ('country', models.CharField(max_length=80, verbose_name='الدولة')),
                ('city', models.CharField(blank=True, max_length=80, verbose_name='المدينة')),
                ('description', models.TextField(help_text='ماذا تقدم الشركة، ولمن، وما الذي يميزها.', verbose_name='نبذة عن الشركة')),
                ('products', models.TextField(blank=True, verbose_name='المنتجات والخدمات')),
                ('usp', models.TextField(blank=True, help_text='لماذا يختار العميل هذه الشركة دون منافسيها؟', verbose_name='نقاط التميز')),
                ('target_audience', models.TextField(blank=True, verbose_name='الجمهور المستهدف')),
                ('competitors', models.TextField(blank=True, verbose_name='المنافسون')),
                ('goals', models.TextField(blank=True, help_text='مثل: زيادة الوعي، جلب عملاء محتملين، زيادة المبيعات.', verbose_name='أهداف التسويق')),
                ('content_language', models.CharField(choices=[('ar_msa', 'العربية الفصحى'), ('ar_local', 'العربية بلهجة السوق المحلي'), ('en', 'الإنجليزية'), ('ar_en', 'العربية والإنجليزية معاً')], default='ar_msa', max_length=10, verbose_name='لغة المحتوى')),
                ('tone', models.CharField(choices=[('professional', 'مهنية وموثوقة'), ('friendly', 'ودودة وقريبة'), ('bold', 'جريئة وحماسية'), ('luxury', 'فاخرة وراقية'), ('playful', 'مرحة وخفيفة'), ('inspiring', 'ملهمة وتحفيزية')], default='professional', max_length=20, verbose_name='نبرة الخطاب')),
                ('voice_notes', models.TextField(blank=True, help_text='عبارات مفضلة، أو أسلوب معين في الكتابة.', verbose_name='ملاحظات على الأسلوب')),
                ('dos', models.TextField(blank=True, verbose_name='ما يجب فعله')),
                ('donts', models.TextField(blank=True, verbose_name='ما يجب تجنبه')),
                ('brand_hashtags', models.CharField(blank=True, help_text='تُضاف إلى المنشورات عند الحاجة، مفصولة بمسافات.', max_length=300, verbose_name='وسوم العلامة')),
                ('primary_color', models.CharField(default='#4F46E5', max_length=7, validators=[django.core.validators.RegexValidator('^#[0-9a-fA-F]{6}$', 'أدخل لوناً بصيغة \u200e#RRGGBB.')], verbose_name='اللون الأساسي')),
                ('secondary_color', models.CharField(default='#0EA5E9', max_length=7, validators=[django.core.validators.RegexValidator('^#[0-9a-fA-F]{6}$', 'أدخل لوناً بصيغة \u200e#RRGGBB.')], verbose_name='اللون الثانوي')),
                ('accent_color', models.CharField(default='#F59E0B', max_length=7, validators=[django.core.validators.RegexValidator('^#[0-9a-fA-F]{6}$', 'أدخل لوناً بصيغة \u200e#RRGGBB.')], verbose_name='لون التمييز')),
                ('heading_font', models.CharField(choices=[('cairo', 'Cairo'), ('tajawal', 'Tajawal'), ('almarai', 'Almarai'), ('plex', 'IBM Plex Sans Arabic'), ('readex', 'Readex Pro'), ('messiri', 'El Messiri'), ('kufi', 'Noto Kufi Arabic'), ('amiri', 'Amiri')], default='cairo', max_length=20, verbose_name='خط العناوين')),
                ('body_font', models.CharField(choices=[('cairo', 'Cairo'), ('tajawal', 'Tajawal'), ('almarai', 'Almarai'), ('plex', 'IBM Plex Sans Arabic'), ('readex', 'Readex Pro'), ('messiri', 'El Messiri'), ('kufi', 'Noto Kufi Arabic'), ('amiri', 'Amiri')], default='tajawal', max_length=20, verbose_name='خط النصوص')),
                ('website', models.CharField(blank=True, max_length=200, verbose_name='الموقع الإلكتروني')),
                ('phone', models.CharField(blank=True, max_length=30, verbose_name='رقم التواصل')),
                ('whatsapp', models.CharField(blank=True, max_length=30, verbose_name='واتساب')),
                ('facebook_page', models.CharField(blank=True, max_length=200, verbose_name='صفحة فيسبوك')),
                ('instagram_handle', models.CharField(blank=True, max_length=100, verbose_name='حساب إنستغرام')),
                ('tiktok_handle', models.CharField(blank=True, max_length=100, verbose_name='حساب تيك توك')),
                ('timezone', models.CharField(choices=[('Africa/Khartoum', 'الخرطوم (GMT+2)'), ('Asia/Qatar', 'الدوحة (GMT+3)'), ('Asia/Riyadh', 'الرياض (GMT+3)'), ('Asia/Dubai', 'دبي (GMT+4)'), ('Africa/Cairo', 'القاهرة'), ('Asia/Kuwait', 'الكويت (GMT+3)'), ('Asia/Muscat', 'مسقط (GMT+4)'), ('Asia/Bahrain', 'المنامة (GMT+3)'), ('Asia/Amman', 'عمّان'), ('Europe/London', 'لندن')], default='Asia/Qatar', max_length=50, verbose_name='المنطقة الزمنية')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'شركة',
                'verbose_name_plural': 'الشركات',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='MediaAsset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.ImageField(height_field='height', upload_to='assets/%Y/%m/', verbose_name='الصورة', width_field='width')),
                ('title', models.CharField(blank=True, max_length=150, verbose_name='الوصف')),
                ('tags', models.CharField(blank=True, help_text='كلمات تساعد في اختيار الصورة المناسبة للمنشور.', max_length=200, verbose_name='الوسوم')),
                ('width', models.PositiveIntegerField(default=0)),
                ('height', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assets', to='companies.company')),
                ('uploaded_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'صورة',
                'verbose_name_plural': 'مكتبة الوسائط',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Membership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('owner', 'المالك'), ('admin', 'مدير'), ('editor', 'محرر محتوى'), ('viewer', 'مشاهد')], default='editor', max_length=10, verbose_name='الدور')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to='companies.company')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'عضوية',
                'verbose_name_plural': 'العضويات',
                'constraints': [models.UniqueConstraint(fields=('company', 'user'), name='unique_company_member')],
            },
        ),
    ]
