# Generated by Django 5.2.17 on 2026-09-30 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='auto_publish',
            field=models.BooleanField(default=False, help_text='انشر المنشورات المعتمدة على الحسابات المربوطة في موعدها.', verbose_name='النشر التلقائي'),
        ),
    ]
