# Generated by Django 5.2.17 on 2026-09-30 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0002_company_auto_publish'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='approved_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='تاريخ الاعتماد'),
        ),
        migrations.AddField(
            model_name='company',
            name='is_active',
            field=models.BooleanField(default=True, help_text='إيقافه يعلّق الاشتراك.', verbose_name='نشط'),
        ),
        migrations.AddField(
            model_name='company',
            name='is_approved',
            field=models.BooleanField(default=True, verbose_name='معتمد'),
        ),
        migrations.AddField(
            model_name='company',
            name='is_demo',
            field=models.BooleanField(default=False, verbose_name='حساب تجريبي'),
        ),
        migrations.AddField(
            model_name='company',
            name='subscription_expires',
            field=models.DateField(blank=True, help_text='فارغ = بدون انتهاء.', null=True, verbose_name='نهاية الاشتراك'),
        ),
        migrations.AddField(
            model_name='company',
            name='subscription_plan',
            field=models.CharField(choices=[('basic', 'أساسي'), ('pro', 'احترافي'), ('enterprise', 'مؤسسات')], default='basic', max_length=20, verbose_name='الباقة'),
        ),
    ]
