# Generated by Django 5.2.17 on 2026-09-30 19:23

import datetime
from django.db import migrations, models


def start_from_creation(apps, schema_editor):
    """Existing subscriptions started when their company was created."""
    Company = apps.get_model('companies', 'Company')
    for company in Company.objects.all():
        company.subscription_start = company.created_at.date()
        company.save(update_fields=['subscription_start'])


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0003_subscription'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='company',
            name='subscription_plan',
        ),
        migrations.AddField(
            model_name='company',
            name='email',
            field=models.EmailField(blank=True, help_text='بريد التواصل مع المشترك.', max_length=254, verbose_name='البريد الإلكتروني'),
        ),
        migrations.AddField(
            model_name='company',
            name='subscription_start',
            field=models.DateField(default=datetime.date.today, verbose_name='بداية الاشتراك'),
        ),
        migrations.RunPython(start_from_creation, migrations.RunPython.noop),
    ]
