# Generated by Django 5.2.17 on 2026-09-30 21:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0004_subscription_details'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='lessons',
            field=models.JSONField(blank=True, default=list, verbose_name='ما تعلّمه وكيل'),
        ),
        migrations.AddField(
            model_name='company',
            name='lessons_updated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
