# Generated by Django 5.2.17 on 2026-09-30 21:55

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0005_learning'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='autopilot',
            field=models.BooleanField(default=False, verbose_name='الطيار الآلي'),
        ),
        migrations.AddField(
            model_name='company',
            name='autopilot_client_email',
            field=models.EmailField(blank=True, help_text='يصله رابط مراجعة الخطة واعتمادها. اتركه فارغاً ليصل الرابط إلى الفريق فقط.', max_length=254, verbose_name='بريد العميل'),
        ),
        migrations.AddField(
            model_name='company',
            name='autopilot_day',
            field=models.PositiveSmallIntegerField(default=25, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(28)], verbose_name='يوم إعداد الخطة'),
        ),
        migrations.AddField(
            model_name='company',
            name='autopilot_platforms',
            field=models.JSONField(blank=True, default=list, verbose_name='المنصات'),
        ),
        migrations.AddField(
            model_name='company',
            name='autopilot_posts_per_week',
            field=models.PositiveSmallIntegerField(default=4, verbose_name='عدد المنشورات أسبوعياً'),
        ),
    ]
