# Generated by Django 5.2.17 on 2026-10-03 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0006_autopilot'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='autopilot',
            field=models.BooleanField(default=False, verbose_name='المخطط الآلي'),
        ),
    ]
