# Generated by Django 5.2.17 on 2026-10-04 21:22

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0007_autopilot_label'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='evergreen_per_month',
            field=models.PositiveSmallIntegerField(default=0, validators=[django.core.validators.MaxValueValidator(8)], verbose_name='منشورات دائمة يُعاد نشرها شهرياً'),
        ),
    ]
