# Generated by Django 5.2.17 on 2026-10-04 21:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0008_copies_and_evergreen'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='client_whatsapp',
            field=models.CharField(blank=True, help_text='يصله كل منشور بزرّي «اعتماد» و«طلب تعديل». مع رمز الدولة، مثل \u200e+97455551234.', max_length=20, verbose_name='واتساب العميل'),
        ),
    ]
