# Generated by Django 5.2.17 on 2026-10-04 21:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0009_whatsapp'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='inbox_auto_reply',
            field=models.BooleanField(default=False, verbose_name='الرد التلقائي على التعليقات البسيطة'),
        ),
    ]
