# Generated by Django 5.2.17 on 2026-10-04 21:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0010_inbox'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='ad_account_currency',
            field=models.CharField(blank=True, max_length=3),
        ),
        migrations.AddField(
            model_name='company',
            name='ad_account_id',
            field=models.CharField(blank=True, max_length=40, verbose_name='الحساب الإعلاني'),
        ),
    ]
