# Generated by Django 5.2.17 on 2026-10-04 21:33

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0011_ads'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Agency',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='اسم الوكالة')),
                ('logo', models.ImageField(blank=True, upload_to='agencies/', verbose_name='شعار الوكالة')),
                ('color', models.CharField(default='#4F46E5', max_length=7, validators=[django.core.validators.RegexValidator('^#[0-9a-fA-F]{6}$', 'أدخل لوناً بصيغة \u200e#RRGGBB.')], verbose_name='لون الوكالة')),
                ('website', models.CharField(blank=True, max_length=200, verbose_name='موقع الوكالة')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('owner', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='agency', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'وكالة',
                'verbose_name_plural': 'الوكالات',
            },
        ),
        migrations.AddField(
            model_name='company',
            name='agency',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='companies', to='companies.agency'),
        ),
    ]
