# Generated by Django 5.2.17 on 2026-09-30 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='status',
            field=models.CharField(choices=[('pending', 'في الانتظار'), ('running', 'قيد التنفيذ'), ('done', 'اكتمل'), ('failed', 'فشل'), ('cancelled', 'أُلغي')], default='pending', max_length=10),
        ),
    ]
