# Generated by Django 5.2.17 on 2026-09-30 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0003_alter_job_kind'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='cache_hit_tokens',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='job',
            name='cost_usd',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='job',
            name='model',
            field=models.CharField(blank=True, max_length=80),
        ),
    ]
