# Generated by Django 5.2.17 on 2026-09-30 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0004_job_cost'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='error_detail',
            field=models.TextField(blank=True),
        ),
    ]
