# Generated by Django 5.2.17 on 2026-09-30 21:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0005_job_error_detail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='kind',
            field=models.CharField(choices=[('generate_plan', 'إعداد خطة المحتوى'), ('rewrite_post', 'إعادة كتابة منشور'), ('render_post', 'تصميم صورة منشور'), ('render_plan', 'تصميم صور الخطة'), ('publish_post', 'نشر منشور'), ('learn', 'التعلّم من الملاحظات')], max_length=20),
        ),
    ]
