# Generated by Django 5.2.17 on 2026-10-04 20:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0006_learning'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='kind',
            field=models.CharField(choices=[('generate_plan', 'إعداد خطة المحتوى'), ('rewrite_post', 'إعادة كتابة منشور'), ('render_post', 'تصميم صورة منشور'), ('render_plan', 'تصميم صور الخطة'), ('publish_post', 'نشر منشور'), ('learn', 'التعلّم من الملاحظات'), ('fetch_insights', 'تحديث أرقام الأداء'), ('generate_report', 'إعداد تقرير الأداء')], max_length=20),
        ),
    ]
