# Generated by Django 5.2.17 on 2026-10-04 21:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0008_copies_and_evergreen'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='kind',
            field=models.CharField(choices=[('generate_plan', 'إعداد خطة المحتوى'), ('rewrite_post', 'إعادة كتابة منشور'), ('render_post', 'تصميم صورة منشور'), ('render_plan', 'تصميم صور الخطة'), ('publish_post', 'نشر منشور'), ('learn', 'التعلّم من الملاحظات'), ('fetch_insights', 'تحديث أرقام الأداء'), ('generate_report', 'إعداد تقرير الأداء'), ('variant_post', 'نسخة بلغة أو لهجة أخرى'), ('repost', 'إعادة نشر محتوى دائم'), ('competitors', 'تحليل المنافسين')], max_length=20),
        ),
    ]
