# Generated by Django 5.2.17 on 2026-10-04 21:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('companies', '0010_inbox'),
        ('content', '0009_copies_and_evergreen'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='InboxItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('platform', models.CharField(max_length=10)),
                ('external_id', models.CharField(max_length=100)),
                ('author', models.CharField(blank=True, max_length=150)),
                ('text', models.TextField(blank=True)),
                ('received_at', models.DateTimeField()),
                ('triaged', models.BooleanField(default=False)),
                ('sentiment', models.CharField(blank=True, choices=[('positive', 'إيجابي'), ('neutral', 'محايد'), ('negative', 'سلبي')], max_length=10)),
                ('category', models.CharField(blank=True, choices=[('question', 'سؤال'), ('complaint', 'شكوى'), ('praise', 'إشادة'), ('spam', 'مزعج'), ('other', 'أخرى')], max_length=10)),
                ('urgency', models.CharField(blank=True, choices=[('low', 'منخفض'), ('normal', 'عادي'), ('high', 'عاجل'), ('crisis', 'أزمة')], max_length=10)),
                ('suggested_reply', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('new', 'جديد'), ('replied', 'تم الرد'), ('dismissed', 'مُتجاهَل')], default='new', max_length=10)),
                ('reply_text', models.TextField(blank=True)),
                ('reply_error', models.CharField(blank=True, max_length=300)),
                ('replied_at', models.DateTimeField(blank=True, null=True)),
                ('auto_replied', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inbox_items', to='companies.company')),
                ('post', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inbox_items', to='content.post')),
                ('replied_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-received_at'],
                'indexes': [models.Index(fields=['company', 'status'], name='inbox_inbox_company_8a22aa_idx')],
                'constraints': [models.UniqueConstraint(fields=('company', 'platform', 'external_id'), name='one_inbox_item_per_comment')],
            },
        ),
    ]
