# Generated by Django 5.2.17 on 2026-09-30 13:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('companies', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ContentPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.DateField(help_text='أول يوم في الشهر.', verbose_name='الشهر')),
                ('platforms', models.JSONField(default=list, verbose_name='المنصات')),
                ('posts_per_week', models.PositiveSmallIntegerField(default=4, verbose_name='عدد المنشورات أسبوعياً')),
                ('brief', models.TextField(blank=True, help_text='عروض، مناسبات، منتجات جديدة، أو أي شيء تريد التركيز عليه.', verbose_name='توجيهات هذا الشهر')),
                ('status', models.CharField(choices=[('generating', 'قيد الإعداد'), ('ready', 'جاهزة'), ('failed', 'تعذّر الإعداد')], default='generating', max_length=12)),
                ('title', models.CharField(blank=True, max_length=200, verbose_name='العنوان')),
                ('summary', models.TextField(blank=True, verbose_name='ملخص الاستراتيجية')),
                ('goals', models.JSONField(blank=True, default=list, verbose_name='الأهداف')),
                ('pillars', models.JSONField(blank=True, default=list, verbose_name='محاور المحتوى')),
                ('key_dates', models.JSONField(blank=True, default=list, verbose_name='المناسبات')),
                ('error', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='plans', to='companies.company')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'خطة محتوى',
                'verbose_name_plural': 'خطط المحتوى',
                'ordering': ['-month', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('platforms', models.JSONField(default=list, verbose_name='المنصات')),
                ('format', models.CharField(choices=[('image', 'تصميم ثابت'), ('carousel', 'منشور متعدد الشرائح'), ('reel', 'فيديو قصير (ريلز / تيك توك)'), ('story', 'قصة (ستوري)')], default='image', max_length=10, verbose_name='نوع المنشور')),
                ('status', models.CharField(choices=[('draft', 'مسودة'), ('review', 'بانتظار المراجعة'), ('approved', 'معتمد'), ('published', 'منشور')], default='draft', max_length=10, verbose_name='الحالة')),
                ('scheduled_at', models.DateTimeField(blank=True, null=True, verbose_name='موعد النشر')),
                ('title', models.CharField(max_length=200, verbose_name='الفكرة')),
                ('pillar', models.CharField(blank=True, max_length=100, verbose_name='المحور')),
                ('objective', models.CharField(blank=True, max_length=100, verbose_name='الهدف')),
                ('caption', models.TextField(blank=True, verbose_name='نص المنشور')),
                ('hashtags', models.CharField(blank=True, max_length=500, verbose_name='الوسوم')),
                ('headline', models.CharField(blank=True, max_length=160, verbose_name='العنوان الرئيسي')),
                ('subheadline', models.CharField(blank=True, max_length=260, verbose_name='العنوان الفرعي')),
                ('cta', models.CharField(blank=True, max_length=80, verbose_name='عبارة الدعوة')),
                ('badge', models.CharField(blank=True, help_text='نص قصير بارز مثل: جديد، خصم 20%.', max_length=40, verbose_name='الشارة')),
                ('template', models.CharField(default='bold', max_length=20, verbose_name='القالب')),
                ('size', models.CharField(choices=[('square', 'مربع 1:1'), ('portrait', 'طولي 4:5'), ('story', 'عمودي 9:16')], default='square', max_length=10, verbose_name='المقاس')),
                ('visual_notes', models.TextField(blank=True, verbose_name='وصف الصورة المقترحة')),
                ('image', models.ImageField(blank=True, upload_to='posts/%Y/%m/', verbose_name='التصميم')),
                ('image_stale', models.BooleanField(default=True, help_text='The design changed since the image was last rendered.')),
                ('video_script', models.TextField(blank=True, verbose_name='سيناريو الفيديو')),
                ('review_note', models.TextField(blank=True, verbose_name='ملاحظات المراجعة')),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('background', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='companies.mediaasset', verbose_name='صورة الخلفية')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='posts', to='companies.company')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('plan', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='posts', to='content.contentplan')),
            ],
            options={
                'verbose_name': 'منشور',
                'verbose_name_plural': 'المنشورات',
                'ordering': ['scheduled_at', 'pk'],
                'indexes': [models.Index(fields=['company', 'scheduled_at'], name='content_pos_company_72ce17_idx')],
            },
        ),
    ]
