# Generated by Django 5.2.17 on 2026-09-30 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='format',
            field=models.CharField(choices=[('image', 'تصميم ثابت'), ('reel', 'فيديو قصير (ريلز / تيك توك)'), ('story', 'قصة (ستوري)')], default='image', max_length=10, verbose_name='نوع المنشور'),
        ),
    ]
