# Generated by Django 5.2.17 on 2026-09-30 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0003_post_comments'),
    ]

    operations = [
        migrations.AddField(
            model_name='contentplan',
            name='share_token',
            field=models.CharField(blank=True, db_index=True, max_length=64),
        ),
    ]
