# Generated by Django 5.2.17 on 2026-09-30 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0004_plan_share_token'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='external_ids',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='post',
            name='publish_attempted_at',
            field=models.DateTimeField(blank=True, help_text='Set when auto-publishing picks the post, so it is tried once.', null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='publish_error',
            field=models.TextField(blank=True),
        ),
    ]
