# Generated by Django 5.2.17 on 2026-09-30 21:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0005_learning'),
        ('content', '0005_post_external_ids_post_publish_attempted_at_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='LearningSignal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('edit', 'تعديل نص'), ('changes', 'طلب تعديل'), ('rewrite', 'طلب إعادة كتابة'), ('comment', 'تعليق العميل')], max_length=10)),
                ('field', models.CharField(blank=True, max_length=30)),
                ('before', models.TextField(blank=True)),
                ('after', models.TextField(blank=True)),
                ('note', models.TextField(blank=True)),
                ('from_client', models.BooleanField(default=False)),
                ('used', models.BooleanField(default=False, help_text='Already distilled into the lessons.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='learning_signals', to='companies.company')),
                ('post', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='content.post')),
            ],
            options={
                'ordering': ['created_at'],
                'indexes': [models.Index(fields=['company', 'used'], name='content_lea_company_707be4_idx')],
            },
        ),
    ]
