# Generated by Django 5.2.17 on 2026-09-30 21:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0006_learning'),
    ]

    operations = [
        migrations.AddField(
            model_name='contentplan',
            name='autopilot',
            field=models.BooleanField(default=False, help_text='Prepared by the autopilot, not by a person.'),
        ),
    ]
