# Generated by Django 5.2.17 on 2026-10-04 20:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0007_autopilot'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='motif',
            field=models.CharField(blank=True, help_text='فارغ = الافتراضية للقالب.', max_length=20, verbose_name='الزخرفة'),
        ),
        migrations.AddField(
            model_name='post',
            name='scheme',
            field=models.CharField(blank=True, help_text='فارغ = الافتراضي للقالب.', max_length=20, verbose_name='نظام الألوان'),
        ),
        migrations.AddField(
            model_name='post',
            name='variant',
            field=models.PositiveIntegerField(default=0, help_text='Seeds the small random differences between designs.'),
        ),
    ]
