# Generated by Django 5.2.17 on 2026-10-04 21:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0008_post_design_layers'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='evergreen',
            field=models.BooleanField(default=False, help_text='صالح لإعادة النشر بصياغة جديدة بعد مدة.', verbose_name='محتوى دائم'),
        ),
        migrations.AddField(
            model_name='post',
            name='language',
            field=models.CharField(blank=True, max_length=12, verbose_name='لغة النسخة'),
        ),
        migrations.AddField(
            model_name='post',
            name='source_post',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='copies', to='content.post'),
        ),
    ]
