# Generated by Django 5.2.17 on 2026-10-05 04:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0009_copies_and_evergreen'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='vectors',
            field=models.JSONField(blank=True, default=list, help_text='Up to three keys of apps.studio.vectors; empty = guessed from the text.', verbose_name='الرسوم'),
        ),
    ]
