# Generated by Django 5.2.17 on 2026-10-04 21:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('companies', '0009_whatsapp'),
        ('content', '0009_copies_and_evergreen'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReviewSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(help_text='Digits only, with the country code.', max_length=20)),
                ('invited_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('awaiting', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='content.post')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='whatsapp_sessions', to='companies.company')),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='whatsapp_sessions', to='content.contentplan')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('plan', 'phone'), name='one_whatsapp_session_per_plan_phone')],
            },
        ),
    ]
