# Generated by Django 5.2.17 on 2026-10-04 21:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('companies', '0011_ads'),
        ('content', '0009_copies_and_evergreen'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AdDraft',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('suggesting', 'قيد الاقتراح'), ('suggested', 'مقترح'), ('created', 'أُنشئ متوقفاً في Meta'), ('failed', 'تعذّر')], default='suggesting', max_length=12)),
                ('daily_budget', models.DecimalField(decimal_places=2, default=5, max_digits=10, verbose_name='الميزانية اليومية')),
                ('days', models.PositiveSmallIntegerField(default=7, verbose_name='عدد الأيام')),
                ('age_min', models.PositiveSmallIntegerField(default=18, verbose_name='العمر من')),
                ('age_max', models.PositiveSmallIntegerField(default=55, verbose_name='العمر إلى')),
                ('gender', models.CharField(choices=[('all', 'الجميع'), ('male', 'رجال'), ('female', 'نساء')], default='all', max_length=6, verbose_name='الجنس')),
                ('countries', models.CharField(blank=True, help_text='رموز الدول، مثل: QA SA AE', max_length=100, verbose_name='الدول')),
                ('rationale', models.TextField(blank=True)),
                ('audience_notes', models.TextField(blank=True)),
                ('campaign_id', models.CharField(blank=True, max_length=40)),
                ('adset_id', models.CharField(blank=True, max_length=40)),
                ('ad_id', models.CharField(blank=True, max_length=40)),
                ('error', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ad_drafts', to='companies.company')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ad_drafts', to='content.post')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
