# Generated by Django 5.2.17 on 2026-10-04 20:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('companies', '0007_autopilot_label'),
        ('content', '0008_post_design_layers'),
    ]

    operations = [
        migrations.CreateModel(
            name='MonthlyReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.DateField(help_text='First day of the month the report covers.')),
                ('status', models.CharField(choices=[('generating', 'قيد الإعداد'), ('ready', 'جاهز'), ('failed', 'تعذّر الإعداد')], default='generating', max_length=12)),
                ('stats', models.JSONField(blank=True, default=dict)),
                ('summary', models.TextField(blank=True)),
                ('wins', models.JSONField(blank=True, default=list)),
                ('recommendations', models.JSONField(blank=True, default=list)),
                ('error', models.TextField(blank=True)),
                ('share_token', models.CharField(blank=True, db_index=True, max_length=64)),
                ('emailed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports', to='companies.company')),
            ],
            options={
                'ordering': ['-month'],
                'constraints': [models.UniqueConstraint(fields=('company', 'month'), name='one_report_per_month')],
            },
        ),
        migrations.CreateModel(
            name='PostInsight',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('platform', models.CharField(max_length=10)),
                ('reach', models.PositiveIntegerField(blank=True, help_text='People who saw it; null when the platform did not say.', null=True)),
                ('likes', models.PositiveIntegerField(default=0)),
                ('comments', models.PositiveIntegerField(default=0)),
                ('shares', models.PositiveIntegerField(default=0)),
                ('saves', models.PositiveIntegerField(default=0)),
                ('fetched_at', models.DateTimeField(auto_now=True)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='insights', to='content.post')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('post', 'platform'), name='one_insight_per_post_platform')],
            },
        ),
    ]
