# Generated by Django 5.2.17 on 2026-10-04 21:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0008_copies_and_evergreen'),
        ('insights', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Competitor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='الاسم')),
                ('website', models.CharField(blank=True, max_length=300, verbose_name='الموقع الإلكتروني')),
                ('social', models.CharField(blank=True, help_text='روابط أو أسماء حسابات، مفصولة بمسافات.', max_length=500, verbose_name='حسابات التواصل')),
                ('sample_posts', models.TextField(blank=True, help_text='الصق نصوص منشورات حديثة لهم أو صف ما ينشرونه؛ يقرأها وكيل في التحليل.', verbose_name='أمثلة من منشوراتهم')),
                ('site_text', models.TextField(blank=True)),
                ('site_read_at', models.DateTimeField(blank=True, null=True)),
                ('site_error', models.CharField(blank=True, max_length=300)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='competitor_list', to='companies.company')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='CompetitorAnalysis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('generating', 'قيد التحليل'), ('ready', 'جاهز'), ('failed', 'تعذّر التحليل')], default='generating', max_length=12)),
                ('summary', models.TextField(blank=True)),
                ('competitors', models.JSONField(blank=True, default=list)),
                ('gaps', models.JSONField(blank=True, default=list)),
                ('opportunities', models.JSONField(blank=True, default=list)),
                ('error', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='competitor_analyses', to='companies.company')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
