# Generated by Django 5.2.17 on 2026-09-30 17:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('companies', '0002_company_auto_publish'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SocialAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('platform', models.CharField(choices=[('facebook', 'فيسبوك'), ('instagram', 'إنستغرام')], max_length=10)),
                ('external_id', models.CharField(help_text='Page ID, or Instagram professional account ID.', max_length=64)),
                ('name', models.CharField(max_length=200)),
                ('access_token', models.TextField()),
                ('last_error', models.TextField(blank=True)),
                ('connected_at', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='social_accounts', to='companies.company')),
                ('connected_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'حساب تواصل',
                'verbose_name_plural': 'حسابات التواصل',
                'constraints': [models.UniqueConstraint(fields=('company', 'platform'), name='one_account_per_platform')],
            },
        ),
    ]
