# Generated by Django 5.2.17 on 2026-10-01 05:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='socialaccount',
            name='refresh_token',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='socialaccount',
            name='token_expires_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='socialaccount',
            name='external_id',
            field=models.CharField(help_text='Page ID, Instagram professional account ID, or TikTok open_id.', max_length=64),
        ),
        migrations.AlterField(
            model_name='socialaccount',
            name='platform',
            field=models.CharField(choices=[('facebook', 'فيسبوك'), ('instagram', 'إنستغرام'), ('tiktok', 'تيك توك')], max_length=10),
        ),
    ]
