# Generated by Django 5.2.17 on 2026-10-04 21:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0002_tiktok'),
    ]

    operations = [
        migrations.AddField(
            model_name='socialaccount',
            name='user_token',
            field=models.TextField(blank=True),
        ),
    ]
